apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cicd-smoketest-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  serviceAccountName: argo
  templates:
  - name: main
    dag:
      tasks:
      - name: invoke-other-builds
        arguments:
          parameters:
          - name: git_repo
            value: "{{ item.git_repo }}"
          - name: git_version
            value: "{{ item.git_version }}"
          - name: git_ref_type
            value: branches
        templateRef:
          name: flavor-git-template
          template: main
        withItems:
          - { git_repo: "https://github.com/bradfordwagner/gh-template-go-lib.git"           , git_version: main}
          - { git_repo: "https://github.com/bradfordwagner/gh-template-go-cli.git"           , git_version: main}
          - { git_repo: "https://github.com/bradfordwagner/gh-template-ansible-playbook.git" , git_version: main}
          - { git_repo: "https://github.com/bradfordwagner/gh-template-ansible-role.git"     , git_version: main}
          - { git_repo: "https://github.com/bradfordwagner/gh-template-tf-module.git"        , git_version: main}
          - { git_repo: "https://github.com/bradfordwagner/gh-template-helm-chart.git"       , git_version: main}
